### PR TITLE
Restore master compatibility.

### PR DESCRIPTION
**Pull request by fire**
@kitsdream This will restore builds on master.

### CODE REVIEW

**Comment by fire** [comment]
Errors:

```

Error: modules/visual_script/editor/visual_script_editor.cpp:2201:37: error: declaration of 'data' shadows a member of 'VisualScriptEditor' [-Werror=shadow]
 2201 |  List<VisualScript::DataConnection> data;
```

**Comment by kitsdream** [comment]
Okay, I will clone the latest code and continue testing and observing.

**Comment by kitsdream** [comment]
I make a pr that I changed 'visual_script.h' what make ‘select from XXX’ show the tree.

**Comment by kitsdream** [comment]
I think it's not very convenient to not display the delete button in the upper right corner of the node when operating. Additionally, it's not very convenient that the node I selected is not highlighted in the minimap after selection.

**Comment by kitsdream** [comment]
The vertical space of the search box displaying the tree diagram is too small, resulting in limited content display. The window can be enlarged or users can be allowed to drag and adjust the proportion and size of the tree diagram window themselves.

**Comment by fire** [comment]
> I think it's not very convenient to not display the delete button in the upper right corner of the node when operating. Additionally, it's not very convenient that the node I selected is not highlighted in the minimap after selection.

The Godot Engine upstream removed the delete button. We'll need to restore.

**Comment by fire** [comment]
@kitsdream You might have to restart from a pr on master, since this is failing.

**Comment by fire** [comment]
Superseded by: https://github.com/godotengine/godot-visual-script/pull/68

**Pull request closed without merging**
