### PR TITLE
Fix the display of the tree diagram and optimize performance

### PR DESCRIPTION
**Pull request by kitsdream**
Fix the display of the tree diagram and optimize performance.

### CODE REVIEW

**Comment by kitsdream** [comment]
After some debugging, the previous issues have been fixed and ready to be merged. Please review.

**Comment by fire** [comment]
Will try to complete review in the next 48 hours.

**Comment by fire** [comment]
I got some time to review.

**Comment by fire** [comment]
Can you revise?

**Comment by kitsdream** [comment]
> Can you revise?

This modification task is quite difficult for me. I was unable to solve the problem of virtual functions not being able to be instantiated before.

**Comment by kitsdream** [comment]
I am trying to continue optimizing the performance of visual_script_property_selector.cpp.

**Comment by fire** [comment]
I'll merge as is and then we can revise.

**Pull request merged**
