### PR TITLE
Restore and fix the issues what make the search box too slow.

### PR DESCRIPTION
**Pull request by kitsdream**
Restore and fix the issues what make the search box too slow.

### CODE REVIEW

**Comment by fire** [comment]
Can you rebase into one commit?

**Comment by kitsdream** [comment]
> Can you rebase into one commit?

Okay, since I'm not very familiar with the Github workflow, I'm still getting used to Github and PR operations. I will familiarize myself with the relevant workflow as soon as possible.

**Comment by fire** [comment]
I forgot about this, sorry for the delay! The github actions will test the code now.

**Comment by fire** [comment]
There is an error here.

```
 In file included from ./core/templates/cowdata.h:35,
                 from ./core/string/ustring.h:37,
                 from ./core/string/string_name.h:35,
                 from ./core/debugger/engine_debugger.h:34,
                 from modules/visual_script/visual_script.h:34,
                 from modules/visual_script/visual_script.cpp:31:
modules/visual_script/visual_script.cpp: In member function 'virtual ScriptInstance* VisualScript::instance_create(Object*)':
modules/visual_script/visual_script.cpp:846:42: error: invalid new-expression of abstract class type 'VisualScriptInstance'
  846 |  VisualScriptInstance *instance = memnew(VisualScriptInstance);
      |                                          ^~~~~~~~~~~~~~~~~~~~
./core/os/memory.h:94:51: note: in definition of macro 'memnew'
   94 | #define memnew(m_class) _post_initialize(new ("") m_class)
      |                                                   ^~~~~~~
In file included from modules/visual_script/visual_script.cpp:31:
modules/visual_script/visual_script.h:411:7: note:   because the following virtual functions are pure within 'VisualScriptInstance':
  411 | class VisualScriptInstance : public ScriptInstance {
      |       ^~~~~~~~~~~~~~~~~~~~
In file included from ./core/debugger/script_debugger.h:34,
                 from modules/visual_script/visual_script.h:35,
                 from modules/visual_script/visual_script.cpp:31:
./core/object/script_language.h:183:15: note: 	'virtual void ScriptInstance::validate_property(PropertyInfo&) const'
  183 |  virtual void validate_property(PropertyInfo &p_property) const = 0;
      |               ^~~~~~~~~~~~~~~~~
./core/object/script_language.h:208:15: note: 	'virtual void ScriptInstance::notification(int, bool)'
  208 |  virtual void notification(int p_notification, bool p_reversed = false) = 0;
      |               ^~~~~~~~~~~~
```

**Comment by fire** [comment]
Thanks.

**Pull request merged**
